name: markdown

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:

      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Install markdownlint-cli2
        run: npm install markdownlint-cli2 --global

      - uses: actions/checkout@v3

      - name: Lint and fix markdown
        run: markdownlint-cli2 --lint "**.md"

      - name: AutoCorrect
        uses: huacnlee/autocorrect-action@main
        with:
          args: "**.md --lint"
