name: unit_test

on:
  - pull_request

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3

      - name: Run test
        run: |
          python -m unittest
